### ISSUE TITLE
open_ontology() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by Free-Username** [jeremymcrae/hpo_similarity#1]
Hi,

i installed the package using pip and tried to run this example using spyder:

from hpo_similarity import open_ontology

graph, alt_ids, obsolete_ids = open_ontology()

#find all descendant terms
graph.get_descendants('HP:0001249')

#get the text for the phenotypic abnormality
graph.nodes['HP:0001249']['name']

I always get the error open_ontology() missing 1 required positional argument: 'path'

How can I solve this problem?

**Comment by jeremymcrae** [comment]
I hadn't set a default value for open_ontology(). This is now fixed in 0331a94ae30ff6c528d642890bb2528e545b6f1c and I've made a new release for pip installation. Sorry about that!
