### ISSUE TITLE
How can I get the information content of a particular phenotype?

### ISSUE THREAD

**Issue by duttaprat** [jeremymcrae/hpo_similarity#3]
I was exploring ```hpo_similarity``` repository for my work. In this regard, I want to use  ```def calculate_information_content(self, term):``` function. But it shows there is zero division error.

Here is my code

```
from hpo_similarity import open_ontology

graph, alt_ids, obsolete_ids = open_ontology()

print (graph.calculate_information_content('HP:0000007'))
```
**The output shows**

```
Traceback (most recent call last):                                                 
File "ic.py", line 15, in <module>                                                                                        
          print (graph.calculate_information_content('HP:0000007'))                                                             
File "/home/pratik/Strand/hpo_similarity/hpo_similarity/similarity.py", line 216, in calculate_information_content        
           self.nodes[term]['info_content'] = -math.log(term_count/self.total_freq)                                           
 ZeroDivisionError: division by zero   
```

Can you please guide me in this regard?

**Comment by jeremymcrae** [comment]
Hi,

You need some population data of terms by sample to calculate the information content for a term. This can be added to the graph with `graph.tally_hpo_terms(sample_data)`

```py
from hpo_similarity import open_ontology

graph, alt_ids, obsolete_ids = open_ontology()

samples = {'sample_1': ['HP:0000007', 'HP:0001249'], 'sample_2': ['HP:0000007']}
graph.tally_hpo_terms(samples)
```

After that you can calculate the information content for terms in the samples:
``` py
>>> graph.calculate_information_content('HP:0000007') # term in all samples
0.0
>>> graph.calculate_information_content('HP:0001249') # term in subset of samples
0.693
>>> graph.calculate_information_content('HP:0001627') # term not in the samples
ValueError: math domain error
```

It's possible it shouldn't raise an error in the last case, instead return nan (i.e. uninformative), but raising an error also seems valid.

**Comment by duttaprat** [comment]
Thanks a lot @jeremymcrae. Can you please tell me from where we can get this population data of terms by sample. As a novice, I don't have so much idea about this population data of terms by samples.

From where you get the following data
```
samples = {'sample_1': ['HP:0000007', 'HP:0001249'], 'sample_2': ['HP:0000007']}
```

Any specific website or you create randomly?

**Comment by jeremymcrae** [comment]
The example above was created randomly, but for your purposes you'd need a large and real cohort with this data available.

As to where to get that from, I've only used them on non-public datasets for rare disease genetics. I don't know of any datasets with public access that contains this information, unfortunately.

**Comment by duttaprat** [comment]
@jeremymcrae thanks a lot for the clarification.
