### ISSUE TITLE
Some Phenotype not found in the ontology.

### ISSUE THREAD

**Issue by duttaprat** [jeremymcrae/hpo_similarity#4]
I think the ontology file is a little old. When I try to find out the details of ```HP:0012629``` it shows an error 

```
HP:0012629 might be in a more recent ontology, see http://human-phenotype-ontology.org. You can define ontology files with --ontology.
```

I have downloaded the recent ontology file from "http://purl.obolibrary.org/obo/hp.obo". But could not understand how to use it as I am using the ```hpo_similarity``` package which is installed using ```pip```

**Comment by jeremymcrae** [comment]
You can use a local hp.obo ontology file with `open_ontology(PATH_TO_OBO_FILE)`. This package contains a version from 2014, so you're definitely better off using a more up-to-date version.

**Comment by duttaprat** [comment]
Thanks.
